# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionLinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=3, max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='exam',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='RevisionLinks.Exam'),
            preserve_default=False,
        ),
    ]
