# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionLinks', '0003_auto_20160905_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
