# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RevisionLinks', '0005_auto_20161005_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('name', models.CharField(max_length=140)),
                ('url', models.URLField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RevisionLinks.ExamBoard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RevisionLinks.Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default=2, max_length=10, unique=True),
        ),
    ]
